### ISSUE TITLE
Improving UX for navigation in main stages

### ISSUE THREAD

**Issue by Speedssster** [Speedssster/cms#7]
### Adding every button in sidebar to related page header section.
so for example there is no need to open Material menu from sidebar then selecting New or Report while we can have it in main content itself and simply click on Report.
this should be done for each stage including:
- material
- production
- final
- sold

P.S: name of both button in page header and sidebar should be same.

**Comment by jughead79** [comment]
solved in #13

**Comment by Speedssster** [comment]
done even better 
last related commit: b296f1b017e29a83853bdd83e003d3bf945f5168
